### ISSUE TITLE
Recommend use of Dependabot to keep modules up-to-date

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#173]
Recommended to create a file `.github/dependabot.yml` in your repository with the following contents:

```yaml
version: 2
updates:
  - package-ecosystem: terraform
    directories: [/terraform/**/*]
    schedule:
      interval: weekly
      day: monday
    groups:
      terraform:
        patterns: ['*']
```

This will configure Dependabot to automatically keep Terraform modules up-to-date 🎉
